name: Copy files to another repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  copy-to-another-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Pushes to another repository
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          # 💡 URLの中に直接トークンを埋め込む、ツール公式推奨の記述にしました
          REPO: 'https://x-access-token:${{ secrets.API_TOKEN_GITHUB }}@github.com/zarimap/zaritsuri.com.git'
          BRANCH: 'main'
          FOLDER: '.'
          CLEAR_GLOBS: '*'
          FORCE_TO_BRANCH: 'true'
