name: Copy files to another repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  copy-to-another-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Pushes to another repository
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          # トークンだけは env で渡します
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          # エラーが出ないよう、設定をすべて with の中にまとめました
          REPO: github.com/zarimap/zaritsuri.com.git
          BRANCH: 'main'  # 💡これで確実に「BRANCHが指定されていない」エラーを防ぎます
          FOLDER: '.'
          CLEAR_GLOBS: '*'
          FORCE_TO_BRANCH: true
